name: Audit

on:
  push:
    branches: [master]
    pull_request:
      branches: [master]

      jobs:

        audit:
          runs-on: ubuntu-20.04

          steps:
            - uses: actions/

            - name: Verify dependencies
              run: go mod verify

            - name: Build
              run: go build  .

            - name: Run go vet
              run: go vet .

            - name: Install staticcheck
              run: go install honnef.co/go/tools/cmd/staticcheck@latest

            - name: Run staticcheck
              run: staticcheck ./...

              #- name: Run tests
              #run: go test -race -vet=off ./...




